### ISSUE TITLE
Ontobee is broken at 5:40pm EST March 1, 2016

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#69] opened 2016-03-01 22:43 UTC
Server is generating 500 server error. For example if you click on an ontology name from the list on the home page.

**Comment by e4ong1031** [comment] 2016-03-01 22:58
The issue is now fixed. Apparently the Virtuoso RDF store crashes periodically. I will configure the server to automatically restart the database every day. Hopefully it will prevent the same problem from happening again.

**Closed by e4ong1031** 2016-03-01 22:58 UTC

**Comment by cmungall** [comment] 2016-03-01 23:31
You might want to also look into nagios etc
