### ISSUE TITLE
Terms in MICRO are missing in Ontobee

### ISSUE THREAD

**Issue by kbeckenrode** [OntoZoo/ontobee#158] opened 2020-10-30 18:06 UTC
A branch from Ontology of Prokaryotic Phenotypic and Metabolic Characters (MICRO) is not found by Ontobee:

distinctively shaped prokaryotic cell, [obo link](http://purl.obolibrary.org/obo/MICRO_0000204), and all of its children cannot be found. 

Let me know if I can provide any futher information

**Comment by yongqunh** [comment] 2020-10-30 23:55
Hi Kelly,

It appears that MICRO is not yet in Ontobee.
Is it an OBO library ontology?

Best,
Oliver

**Comment by kbeckenrode** [comment] 2020-11-01 17:20
Hi Oliver,

The MICRO ontology is a OBO library ontology.Here is the link to it [Ontology of Prokaryotic Phenotypic and Metabolic Characters](http://www.obofoundry.org/ontology/micro.html)

Talk to you soon! Thanks for your guidance.

**Comment by yongqunh** [comment] 2020-11-03 02:46
I see.
We will check this out.
Thanks,
Oliver

**Comment by yongqunh** [comment] 2020-11-03 16:42
This has now been fixed by Edison Ong.

The problem wasa caused by the invalid language definition in Micro ontology: 

---
1. MICRO_0000541 & MICRO_0000543
<obo:IAO_0000119 xml:lang="25 °c"> ... </obo:IAO_0000119>

2. MICRO_0001571
<obo:IAO_0000119 xml:lang="25°c    * adjusted as required to meet performance standards   directions suspend 46g in 1 litre of distilled water. sterilise by autoclaving at 121°c for 15 minutes. cool to 50-55°c and aseptically add 5-10% sterile defibrinated horse blood sr0050.  mix well and pour into sterile petri dishes."> ... </obo:IAO_0000119>

3. MICRO_0001781
<obo:IAO_0000119 xml:lang="25°c  directions suspend 64 grams in 1 litre of distilled water and soak for 15 minutes, with occasional stirring. distribute into 18mm diameter tubes to a depth of 50mm so that the bottom of the tube is filled with liver particles. agitate frequently during distribution to keep the liver tissue in suspension.  sterilise by autoclaving for 20 minutes at 115° c. inoculate when cool and then aseptically seal with a layer of sterile 2% oxoid agar no.3 (lp0013) solution.  description a liver infusion medium, containing liver particles, for the examination of foods for saccharolytic or putrefactive mesophilic and thermophilic anaerobes. also recommended for the maintenance of aerobes and anaerobes in pure culture.  technique gillespie in communication with scarr1 recommended liver broth for the examination of canners’ sugar for hydrogen swells caused by thermophilic anaerobes (clostridium thermosaccharolyticum). a 20% w/v solution of the sugar is steamed for 30 minutes to destroy vegetative forms and inoculated into liver broth sealed with agar. the standard proposed was a maximum of 1 positive tube in six - with 20ml inocula incubated for 72 hours at 56°c.  this medium should be made up only when required for use. storage of the reconstituted medium is not recommended because air may be absorbed and the re-steaming necessary for the restoration of anaerobic conditions darkens the medium. liver broth is not an homogeneous medium; consisting of a layer of liver particles and a cloudy supernatant. growth produces an obvious increase in turbidity and some organisms (e.g. clostridium thermosaccharolyticum) also produce gas which often pushes the agar plug towards the top of the tube. some organisms also digest the solid liver tissue.  storage conditions and shelf life store the dehydrated medium at 10-30°c and use before the expiry date on the label. store the prepared medium at 2-8° c.  appearance dehydrated medium: brown powder / granules prepared medium: dark brown solution / particles"> ... </obo:IAO_0000119>
---

You can see the xml:lang definition is incorrect. In particular, MICRO_0001781 has an extremely long definition and makes Virtuoso unable to process it. 

After fixing it, Ontobee daily auto-update script should be able to correctly update Micro ontology.

**Closed as completed by yongqunh** 2020-11-03 16:42 UTC

**Comment by yongqunh** [comment] 2020-11-03 16:45
Note that we corrected the problem and stored a local copy of Micro, and Ontobee was specified to use the local version.

Please let us know once the MICRO developers fixed the problem so that we can change it back to auto-update.

Thanks,
Edison & Oliver
