### ISSUE TITLE
Loading GEO on Ontobee

### ISSUE THREAD

**Issue by mcourtot** [OntoZoo/ontobee#41] opened 2015-05-13 22:31 UTC
From http://purl.obolibrary.org/obo/geo.owl

Thanks,
Melanie

**Comment by ontoden** [comment] 2015-05-15 22:12
Loading GEO failed.

The error messages:
--
Loading RDF store:
geo: loading data from http://purl.obolibrary.org/obo/geo.owl
geo: getting final url http://purl.obolibrary.org/obo/geo.owl
Coult not load ontology:
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://www.ifomis.org/bfo/1.1> Cause: Problem parsing http://www.ifomis.org/bfo/1.1
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) OWLOBOParser
6) KRSS2OWLParser
7) ManchesterOWLSyntaxOntologyParser


Detailed logs:
--------------------------------------------------------------------------------
Parser: RDFXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLFunctionalSyntaxOWLParser
Encountered " <ERROR> "< "" at line 1, column 1.
Was expecting:
    "Ontology" ...
     (Line 0)

--------------------------------------------------------------------------------
Parser: TurtleOntologyParser
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered "" at line 1, column 1.
Was expecting one of:


--------------------------------------------------------------------------------
Parser: OWLOBOParser
org.coode.owlapi.obo.parser.TokenMgrError: Lexical error at line 1, column 51.  Encountered: "\n" (10), after : ""

--------------------------------------------------------------------------------
Parser: KRSS2OWLParser
de.uulm.ecs.ai.owlapi.krssparser.ParseException: Encountered " ">" "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"> "" at line 1, column 1.
Was expecting:
    <EOF>


--------------------------------------------------------------------------------
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)


        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1077)
        at org.coode.owlapi.owlxmlparser.OWLImportsHandler.endElement(OWLImportsHandler.java:28)
        at org.coode.owlapi.owlxmlparser.OWLXMLParserHandler.endElement(OWLXMLParserHandler.java:895)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLNSDTDValidator.endNamespaceScope(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.handleEndElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:392)
        at org.coode.owlapi.owlxmlparser.OWLXMLParser.parse(OWLXMLParser.java:47)
        at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:165)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:687)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:628)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:602)
        at org.hegroup.rdfstore.OWLMerge.main(OWLMerge.java:65)
Caused by: org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing http://www.ifomis.org/bfo/1.1
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) OWLOBOParser
6) KRSS2OWLParser
7) ManchesterOWLSyntaxOntologyParser


Detailed logs:
--------------------------------------------------------------------------------
Parser: RDFXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLFunctionalSyntaxOWLParser
Encountered " <ERROR> "< "" at line 1, column 1.
Was expecting:
    "Ontology" ...
     (Line 0)

--------------------------------------------------------------------------------
Parser: TurtleOntologyParser
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered "" at line 1, column 1.
Was expecting one of:


--------------------------------------------------------------------------------
Parser: OWLOBOParser
org.coode.owlapi.obo.parser.TokenMgrError: Lexical error at line 1, column 51.  Encountered: "\n" (10), after : ""

--------------------------------------------------------------------------------
Parser: KRSS2OWLParser
de.uulm.ecs.ai.owlapi.krssparser.ParseException: Encountered " ">" "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"> "" at line 1, column 1.
Was expecting:
    <EOF>


--------------------------------------------------------------------------------
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)


        at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:197)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:687)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:628)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1045)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1070)
        ... 21 more
geo: loading data from http://purl.obolibrary.org/obo/geo.owl
geo: getting final url http://purl.obolibrary.org/obo/geo.owl
Coult not load ontology:
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://www.ifomis.org/bfo/1.1> Cause: Problem parsing http://www.ifomis.org/bfo/1.1
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) OWLOBOParser
6) KRSS2OWLParser
7) ManchesterOWLSyntaxOntologyParser


Detailed logs:
--------------------------------------------------------------------------------
Parser: RDFXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLFunctionalSyntaxOWLParser
Encountered " <ERROR> "< "" at line 1, column 1.
Was expecting:
    "Ontology" ...
     (Line 0)

--------------------------------------------------------------------------------
Parser: TurtleOntologyParser
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered "" at line 1, column 1.
Was expecting one of:


--------------------------------------------------------------------------------
Parser: OWLOBOParser
org.coode.owlapi.obo.parser.TokenMgrError: Lexical error at line 1, column 51.  Encountered: "\n" (10), after : ""

--------------------------------------------------------------------------------
Parser: KRSS2OWLParser
de.uulm.ecs.ai.owlapi.krssparser.ParseException: Encountered " ">" "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"> "" at line 1, column 1.
Was expecting:
    <EOF>


--------------------------------------------------------------------------------
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)


        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1077)
        at org.coode.owlapi.owlxmlparser.OWLImportsHandler.endElement(OWLImportsHandler.java:28)
        at org.coode.owlapi.owlxmlparser.OWLXMLParserHandler.endElement(OWLXMLParserHandler.java:895)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLNSDTDValidator.endNamespaceScope(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.handleEndElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:392)
        at org.coode.owlapi.owlxmlparser.OWLXMLParser.parse(OWLXMLParser.java:47)
        at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:165)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:687)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:628)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:602)
        at org.hegroup.rdfstore.OWLMerge.main(OWLMerge.java:65)
Caused by: org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing http://www.ifomis.org/bfo/1.1
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) OWLOBOParser
6) KRSS2OWLParser
7) ManchesterOWLSyntaxOntologyParser


Detailed logs:
--------------------------------------------------------------------------------
Parser: RDFXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLXMLParser
org.xml.sax.SAXParseException; systemId: http://www.ifomis.org/bfo/1.1; lineNumber: 1; columnNumber: 50; White spaces are required between publicId and systemId.

--------------------------------------------------------------------------------
Parser: OWLFunctionalSyntaxOWLParser
Encountered " <ERROR> "< "" at line 1, column 1.
Was expecting:
    "Ontology" ...
     (Line 0)

--------------------------------------------------------------------------------
Parser: TurtleOntologyParser
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered "" at line 1, column 1.
Was expecting one of:


--------------------------------------------------------------------------------
Parser: OWLOBOParser
org.coode.owlapi.obo.parser.TokenMgrError: Lexical error at line 1, column 51.  Encountered: "\n" (10), after : ""

--------------------------------------------------------------------------------
Parser: KRSS2OWLParser
de.uulm.ecs.ai.owlapi.krssparser.ParseException: Encountered " ">" "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"> "" at line 1, column 1.
Was expecting:
    <EOF>


--------------------------------------------------------------------------------
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)


        at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:197)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:687)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:628)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1045)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1070)
        ... 21 more
Failed to download owl file!
Done!
--

Oliver

**Comment by e4ong1031** [comment] 2015-11-24 21:53
GEO is already loaded into Ontobee.

I am closing this issue. Thanks.

**Closed by e4ong1031** 2015-11-24 21:53 UTC
