### ISSUE TITLE
Missing closing parenthesis in axiom list

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#83] opened 2016-06-26 18:12 UTC
For example on this page: http://purl.obolibrary.org/obo/OBI_0200111
there should be a ")" at the end of the first and fourth lines.

1. has_specified_output only (graph or image
1. has_specified_input only data item
1. has_specified_input some data item
1. has_specified_output some (graph or image
1. planned process

**Comment by e4ong1031** [comment] 2016-06-29 17:01
The problem is now fixed. Thank you and I am closing this issue.

**Closed by e4ong1031** 2016-06-29 17:01 UTC
